### ISSUE TITLE
Clarification of inner closures

### ISSUE THREAD

**Issue by bmeck** [hax/proposal-function-this#2]
Inner closures like the direct eval example in the README seem to need some extra clarification. Particularly I would expect:

```mjs
function foo() {
  const bar = () => this;
}
```

`foo.thisArgumentExpected` to equal `true` since the `this` comes from the `foo` environment record specifying that it does have a this binding per [HasThisBinding](https://tc39.es/ecma262/#sec-function-environment-records-hasthisbinding) and `bar` resolving a reference to that statically.

**Comment by hax** [comment]
@bmeck Thank you for the suggestion, I add a new section for some complex examples, is that ok?

**Comment by bmeck** [comment]
Yes, thanks
